### ISSUE TITLE
python main.py --mode train

### ISSUE THREAD

**Issue by zysNLP** [nouhadziri/THRED#1]
Excuse me, in the following command:
python main.py --mode train --config <YAML_FILE> \
--train_data <TRAIN_DATA> --dev_data <DEV_DATA> --test_data <TEST_DATA> \
--model_dir <MODEL_DIR>

Does YAML_FILE means .yml file as thred_medium.yml? 
But where are the TRAIN_DATA,DEV_DATA and TEST_DATA? Does it means I should download all the .bz2 files you mentioned in THRED/corpora/reddit/README.rd——“Reddit monthly data needs to be downloaded from here for comments and here for submissions”?

**Comment by nouhadziri** [comment]
Thanks for you interest in our work!

Any Yaml file (including the [thred_medium.yml](https://github.com/nouhadziri/THRED/blob/master/conf/thred_medium.yml)) in the [conf](https://github.com/nouhadziri/THRED/tree/master/conf) folder would work. It depends on what model you want to train.

We've had some difficulties to publish the data. However, the issues are mostly resolved and we will publish the data soon. In the mean time, you can build the data from scratch based on the doc provided [here](https://github.com/nouhadziri/THRED/blob/master/corpora/reddit).

**Comment by zysNLP** [comment]
Ok,thank you very much.Expect publish data sets.
