### ISSUE TITLE
Confused about the topic attention in the original paper

### ISSUE THREAD

**Issue by Helicqin** [nouhadziri/THRED#11]
Sorry to bother you with this. I have read your great paper, but some confusion about the topic attention. 

In the paper, you said: 
> The topic words {t1,t2,...,tn} are then linearly combined to form a fixed-length vector k. The weight values are calculated as the following: 
![捕获](https://user-images.githubusercontent.com/21177644/58144425-02233d00-7c81-11e9-9915-45e22f2b84d1.PNG)

I hardly figure it out. Is it the same as normal query-key-value attention? In my opinion,  the final context-level encoder hidden state serves as a query, the word embedding of topic words serve as values. But how are the weights \beta calculated?

Look forward to your reply! Thanks.

**Comment by ehsk** [comment]
Thanks for your interest in our work.
Your guess is correct. It is a regular attention and the equation for learning the weights is as follows:

![image](https://user-images.githubusercontent.com/1574406/58828904-b74fe080-8603-11e9-9d41-479a04f51e28.png)

We have made a few changes (including this one) in the paper, which will be published shortly.

**Comment by Helicqin** [comment]
Thanks for your reply!
