### ISSUE TITLE
fastText with magnitude causes issues

### ISSUE THREAD

**Issue by sashank06** [nouhadziri/THRED#13]
When loading fastText embedding with Magnitude, it causes the following error attached in the screenshot. This error popped up when I was running the Topic Aware model with the default configuration provided in the taware_small.yml file.
![Screen Shot 2019-06-12 at 6 48 27 PM](https://user-images.githubusercontent.com/8636933/59391625-e6bcc680-8d42-11e9-9b59-aef4a6928093.png)

**Comment by ehsk** [comment]
I wasn't able to reproduce the error. Seems the downloaded file by Pymagnitude is broken. Try removing the ".magnitude" folder, located in the project base directory and rerun the training.
