### ISSUE TITLE
how to use it for only 2 turns? Any ideas?

### ISSUE THREAD

**Issue by Monica9502** [nouhadziri/THRED#18]

**Comment by ehsk** [comment]
The Vanilla Seq2Seq and TA-Seq2Seq models can be used for 2-turn dialogues. In the data file, each utterance should be separated by TAB.
Note that THRED and HRED need context to generate a response and therefore, cannot be used for 2-turn dialogues.

**Comment by Monica9502** [comment]
Got it, thanks.
