### ISSUE TITLE
about using other dataset

### ISSUE THREAD

**Issue by zh215021** [nouhadziri/THRED#2]
Hi, thank you for your work. I have a question about the input data.
If I want to use my own data, how can I build a dataset?
each line corresponds to a single conversation,just like this: q1 \t a1 \t q2 \t a2 \t  |  topic word
I don't know if the fact is that I understand it.
thanks again~

**Comment by ehsk** [comment]
Thanks for reaching out.
As you said, each line represents a single conversation. Utterances are separated by TAB. Topic words come after the last utterance with a vertical bar delimiter, so the format would be something like this:
q1 \t a1 \t q2 \t a2  |  topic words
Note that there is no TAB after the last utterance (i.e., a2) and two spaces should come before and after the vertical bar. Please take a look at [this](https://github.com/nouhadziri/THRED/files/2751725/sample_input.txt) sample file.

**Comment by zh215021** [comment]
thank you for your help~
