### ISSUE TITLE
topic model for short text

### ISSUE THREAD

**Issue by Monica9502** [nouhadziri/THRED#21]
Hi, I have tried to build LDA model by gensim using my customed data for short text like twitter, however, the topic words seem not very fine-grained like yours, which is a commom problem of LDA model for short text. Do you have any suggestions for this? Thanks!

**Comment by ehsk** [comment]
You can use [TwitterLDA](https://github.com/minghui/Twitter-LDA) [1] for topic modeling in short documents. You may also find [this](https://towardsdatascience.com/short-text-topic-modeling-70e50a57c883) article useful.

[1] Zhao, W.X., Jiang, J., Weng, J., He, J., Lim, E.P., Yan, H. and Li, X., "Comparing twitter and traditional media using topic models," In ECIR 2011.
