### ISSUE TITLE
output directory not specified. pass it using: -o OR --out-dir

### ISSUE THREAD

**Issue by Zengpr** [nouhadziri/THRED#3]
I have the problem: 
sudo sh bin/reddit.sh -c data/RC__2018-10.xz --log log/log.txt -o output/output.txt

\bin/Reddit.sh: 9: bin/Reddit.sh: [[: not found
-e output directory not specified. pass it using: -o OR --out-dir
why?

**Comment by ehsk** [comment]
The script is written in bash not shell (sh). Please try the following command:

`
bash bin/reddit.sh -c data/RC__2018-10.xz --log log/log.txt -o output/output.txt
`

Also, the script does not need root privileges to run.
