### ISSUE TITLE
No such file or directory: 'src/redis-server': 'src/redis-server'

### ISSUE THREAD

**Issue by Zengpr** [nouhadziri/THRED#7]
when I execute the command:
export PYTHONPATH="."; python3.6 corpora/reddit/reddit_dialogue.py build --text_file output/RC_2018-10.txt --db_file output/RC_2018-10_db.csv --output output1

it traceback：
No such file or directory: 'src/redis-server': 'src/redis-server'

**Comment by ehsk** [comment]
Thanks for raising the issue. We fixed the problem. Please test and let us know if it is still not working.
