### ISSUE TITLE
GPU-Util is low

### ISSUE THREAD

**Issue by shark-3** [nouhadziri/THRED#9]
The GPU-Util is very low ( mostly 0 ) and the CPU utilizes above 1000%.
I installed tensorflow-gpu==1.8. And I used CUDA_VISIBLE_DEVICES to assign GPU to training.

**Comment by ehsk** [comment]
Seems odd! Which model are you running? Also, can you make sure that you don't have tensorflow-cpu installed in your environment?

**Comment by shark-3** [comment]
I used baseline model HRED and I am sure that I installed tensorflow-gpu=1.8.0. Sometimes the GPU-Util will be above 20%, but 0% most of the time. 
![UQ{)8YFY_BFGYCZY3`9X`DN](https://user-images.githubusercontent.com/38354339/55848450-8f9e4800-5b7f-11e9-9b4b-76269823bc22.png)

**Comment by shark-3** [comment]
> Seems odd! Which model are you running? Also, can you make sure that you don't have tensorflow-cpu installed in your environment?

I used baseline model HRED and I am sure that I installed tensorflow-gpu=1.8.0. Sometimes the GPU-Util will be above 20%, but 0% most of the time.
![UQ{)8YFY_BFGYCZY3`9X`DN](https://user-images.githubusercontent.com/38354339/55848481-aa70bc80-5b7f-11e9-9e2a-f7efc808b6b8.png)

**Comment by ehsk** [comment]
Could you turn on "log_device" in the config file and share the log with us?

**Comment by shark-3** [comment]
> Could you turn on "log_device" in the config file and share the log with us?

I sent it to your email. Thank you very much for your reply!
